# Generated by Django 5.1.1 on 2024-09-17 11:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_moodentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoodEntry',
        ),
        migrations.AlterField(
            model_  name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
